# SEO Values
title: Resumos CM
tagline: Resumos para alunos de CM
description: Resumos para alunos de CM
url: https://elcascavel.github.io/ResumosCM/

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Cascavel
  owner_url: https://github.com/elcascavel
  repository_url: https://github.com/elcascavel/ResumosCM

show_downloads: false
show_header: true

sass:
    style: compressed

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-merlot
