# SEO Values
title: Resumos CM
tagline: Resumos para alunos de CM
description: Resumos para alunos de CM
url: https://elcascavel.github.io/ResumosCM/
twitter: https://twitter.com/zenorocha
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Cascavel
  owner_url: https://github.com/elcascavel
  repository_url: https://github.com/elcascavel/ResumosCM

show_downloads: false
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-merlot