# SEO Values
title: Resumos CM
tagline: Resumos para alunos de CM
description: Resumos para alunos de CM

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Cascavel
  owner_url: https://github.com/elcascavel
  repository_url: https://github.com/elcascavel/ResumosCM

show_downloads: false
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
